# Generated by Django 4.0.5 on 2022-06-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copyright',
            options={'ordering': ['-text']},
        ),
        migrations.RenameField(
            model_name='copyright',
            old_name='label',
            new_name='text',
        ),
    ]
