# Generated by Django 4.0.5 on 2022-06-16 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0003_album_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
