# Generated by Django 4.0.5 on 2022-06-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyapp', '0006_remove_albumavailablemarket_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(to='spotifyapp.track'),
        ),
    ]
